// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hqwqzxdnhhznitltirak.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imhxd3F6eGRuaGh6bml0bHRpcmFrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzQ1MjQzMTAsImV4cCI6MjA5MDEwMDMxMH0.n2jA4f_sya18JH-bqVPHP3I-rGGcyNcWYjmk1BFV6CY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});